import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

test('MV3 확장프로그램이 activeTab 증거 수집과 Intake POST를 선언한다', async () => {
  const manifest = JSON.parse(await readFile(new URL('../extension/manifest.json', import.meta.url), 'utf8'));
  const popup = await readFile(new URL('../extension/popup.js', import.meta.url), 'utf8');
  const popupHtml = await readFile(new URL('../extension/popup.html', import.meta.url), 'utf8');
  assert.equal(manifest.manifest_version, 3);
  assert.ok(manifest.permissions.includes('activeTab'));
  assert.ok(manifest.permissions.includes('scripting'));
  assert.equal(manifest.action.default_popup, 'popup.html');
  assert.equal(manifest.background.service_worker, 'background.js');
  assert.ok(manifest.host_permissions.includes('https://www.threads.com/*'));
  assert.ok(manifest.host_permissions.includes('https://www.instagram.com/*'));
  assert.match(popup, /chrome\.scripting\.executeScript/);
  assert.match(popup, /og:description/);
  assert.match(popup, /og:image/);
  assert.match(popup, /og:image:secure_url/);
  assert.match(popup, /isThreadsContentMedia/);
  assert.match(popup, /scontent-/);
  assert.match(popup, /querySelectorAll\('img'\)/);
  assert.match(popup, /og:url/);
  assert.match(popup, /reels/);
  assert.match(popup, /post-caption/);
  assert.match(popup, /영상이 아니라 캡션만 본문/);
  assert.match(popup, /evidenceText/);
  assert.match(popup, /slice\(0, 2000\)/);
  assert.match(popup, /published_at/);
  assert.match(popup, /capture_status/);
  assert.match(popup, /PAGE_ACCESS_REQUIRED/);
  assert.match(popup, /CANONICAL_POST_MISMATCH/);
  assert.match(popup, /captureTabEvidence/);
  assert.match(popup, /현재 게시물 본문을 불러오는 중/);
  assert.match(popup, /renderedPostUrl/);
  assert.match(popup, /captionNode/);
  assert.match(popup, /renderedPostIdentities/);
  assert.match(popup, /isStaleInstagramCapture/);
  assert.match(popup, /maxAttempts = 5/);
  assert.match(popup, /normalizedInstagramAuthor/);
  assert.match(popup, /const threadsPostTitle = platform === 'threads' \? cleanText\(document\.title\) : ''/);
  assert.match(popup, /hasThreadsPostTitle \? threadsPostTitle : domText/);
  assert.match(popup, /RENDERED_POST_MISMATCH/);
  assert.match(popup, /\/v1\/intakes/);
  assert.match(popup, /source_type: 'page_evidence'/);
  assert.match(popup, /chrome\.tabs\.create/);
  assert.match(popupHtml, /내 정리함 열기/);
  assert.doesNotMatch(popup, /result\.dashboard_url/);
});
